### ISSUE TITLE
Couldn't find the executable zenity in the path

### ISSUE THREAD

**Issue by pluveto** [shubham-gupta-16/multi_image_picker_view#22]
OS: Manjaro Linux x86_64

Error Log:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Couldn't find the executable zenity in the path.
#0      isExecutableOnPath (package:file_picker/src/utils.dart:60:5)
<asynchronous suspension>
#1      FilePickerLinux._getPathToExecutable (package:file_picker/src/linux/file_picker_linux.dart:119:14)
<asynchronous suspension>
#2      FilePickerLinux.pickFiles (package:file_picker/src/linux/file_picker_linux.dart:22:31)
<asynchronous suspension>
#3      MultiImagePickerController.pickImages (package:multi_image_picker_view/src/multi_image_picker_controller.dart:39:32)
<asynchronous suspension>
#4      _MultiImagePickerViewState._pickImages (package:multi_image_picker_view/src/multi_image_picker_view.dart:124:20)
<asynchronous suspension>


```

Code:

```dart
  final controller = MultiImagePickerController();

// ...
                Material(
                  child: MultiImagePickerView(
                    controller: controller,
                    padding: const EdgeInsets.all(10),
                  ),
                ),
```

**Comment by pluveto** [comment]
This can be solved by `yay -S zenity`, but I think this is a very heavy dependency (almost 100MB)

**Comment by shubham-gupta-16** [comment]
Version `1.0.0` is released with **Major Changes** 🚀.

**The package no longer handles the image-picking logic**. You have to define your picker logic as you want. You can either choose `image_picker` or `file_picker` or any plugin you want with your own image/file picking logic. This will give you more flexibility and control.

This issue occurred in the `file_picker` package which was used earlier. Since this package now only handles the UI for the image picker, this issue will no longer exist, at least for this package.

Check the README.md for docs and migrating guidelines.
