### ISSUE TITLE
Misleading Name - Not a Regular Image Picker, it's a File Picker that Supports Image Files.

### ISSUE THREAD

**Issue by globemediaofficial** [shubham-gupta-16/multi_image_picker_view#4]
I found this package thinking it was exactly what I needed, implemented it, and then got extremely disappointed. I was expecting something like the image_picker package which uses the photo gallery on mobile devices but instead, this uses the files (at least on iOS, haven't tested it on Android). Since almost all photos on a mobile device are stored in the gallery I'd like to see that added as an option. This was a great package idea but the name is misleading.

**Comment by shubham-gupta-16** [comment]
@globemediaofficial I earlier tried to start it by using `image_picker` library but the problem was that their is no option for restricting on file-type/extension. That's why I choose `file_picker`. 

I am a newbie at Flutter as I started with Android and start exploring flutter 6 months ago. Even this is my first flutter library. Can you help me to suggest what I should do to make this library more useful?

I have few options:
1. Use `image_picker` instead of `file_picker`
2. Stay with `file_picker` and make it more reliable
3. Stop using any image picking library and make this library independent. Then this library provide only the view and its handling. It's upto user to choose what image picking library they want to use. (In contoller, they have to pass a callback function which returns Future of list of images.)

**Comment by xalgia** [comment]
I would highly recommend against using image_picker because it doesn't support Windows, Linux, or MacOs, which could be a deal breaker for people creating cross-platform apps.

**Comment by globemediaofficial** [comment]
> I would personally recommend against using image_picker because it doesn't support Windows, Linux, or MacOs, which could be a deal breaker for people creating cross-platform apps.

My idea for a fix was to use image_picker for iOS and Android, then use the file picker for other platforms. I think that using a file picker on mobile is already a deal-breaker for most, just because most people don’t store photos that way. I’m not too invested in this, though, because I’ve switched to React Native.

**Comment by shubham-gupta-16** [comment]
Version `1.0.0` is released with major changes.

**The package no longer handles the image-picking logic**. You have to define your picker logic as you want. You can either choose `image_picker` or `file_picker` or any plugin you want with your own image/file picking logic. This will give you more flexibility and controls.

Check the README.md for docs and migrating guidelines.
